package com.provys.provysdb.dbcontext;

import java.sql.Connection;

/**
 * Provys specific wrapper on connection. Returns Provys specific wrappers on statements, that
 * provide retrieval of application specific data-types
 */
public interface DbConnection extends Connection {

  @Override
  DbStatement createStatement();

  @Override
  DbStatement createStatement(int resultSetType, int resultSetConcurrency);

  @Override
  DbStatement createStatement(int resultSetType, int resultSetConcurrency,
      int resultSetHoldability);

  @Override
  DbPreparedStatement prepareStatement(String sql);

  @Override
  DbPreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
      int resultSetHoldability);

  @Override
  DbPreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency);

  @Override
  DbPreparedStatement prepareStatement(String sql, int autoGeneratedKeys);

  @Override
  DbPreparedStatement prepareStatement(String sql, int[] columnIndexes);

  @Override
  DbPreparedStatement prepareStatement(String sql, String[] columnNames);

  @Override
  DbCallableStatement prepareCall(String sql);

  @Override
  DbCallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency);

  @Override
  DbCallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
      int resultSetHoldability);
}
