package com.provys.provysdb.dbcontext;

import java.sql.*;

public interface DbConnection extends Connection {
    @Override
    DbStatement createStatement() throws SQLException;

    @Override
    DbPreparedStatement prepareStatement(String sql) throws SQLException;

    @Override
    DbCallableStatement prepareCall(String sql) throws SQLException;

    @Override
    DbStatement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException;

    @Override
    DbPreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;

    @Override
    DbCallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;

    @Override
    DbCallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;

    @Override
    DbPreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;

    @Override
    DbPreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException;

    @Override
    DbPreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException;
}
