package com.provys.provysdb.dbcontext;

import java.sql.*;

public interface ProvysConnection extends Connection {
    @Override
    ProvysStatement createStatement() throws SQLException;

    @Override
    ProvysPreparedStatement prepareStatement(String sql) throws SQLException;

    @Override
    ProvysCallableStatement prepareCall(String sql) throws SQLException;

    @Override
    ProvysStatement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException;

    @Override
    ProvysPreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;

    @Override
    ProvysCallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;

    @Override
    ProvysCallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;

    @Override
    ProvysPreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;

    @Override
    ProvysPreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException;

    @Override
    ProvysPreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException;
}
